version: '3.9'

networks:
  cleanarr_default:
    external: true

services:
  nginx:
    image: "nginx:alpine"
    container_name: nginx
    restart: always
    volumes:
      - /portainer/Files/AppData/Config/dscan/nginx:/etc/nginx/conf.d
      - /portainer/Files/AppData/Config/dscan/dscantool/static:/dscantool/static
    ports:
      - 6585:80
    networks:
      - cleanarr_default

  dscan:
    build:
      context: https://github.com/kaspaeve/dscantool.git
    container_name: dscan
    restart: always
    environment:
      - DSCAN_ALLOWED_HOST=dscan.localdomain
      - DSCAN_DB_HOST=dscan_postgres
      - ALLOWED_HOSTS=192.168.1.14,dscan.localdomain
    volumes:
      - /portainer/Files/AppData/Config/dscan/dscantool/static:/dscantool/static
    depends_on:
      - dscan_postgres
    networks:
      - cleanarr_default
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  dscan_postgres:
    image: "postgres:15-alpine"
    container_name: dscan_postgres
    restart: always
    environment:
      - POSTGRES_DB=dscantool
      - POSTGRES_USER=dscantool
      - POSTGRES_PASSWORD=dscantool
    networks:
      - cleanarr_default
    volumes:
      - /portainer/Files/AppData/Config/dscan/postgres/data:/var/lib/postgresql/data
